# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  webapp:
    image: webapp
    build:
      context: .
      dockerfile: Webapp/Dockerfile
    ports:
      - 80