version: '3.4'

services:
  webapp:
    container_name: webapp
    image: webapp
    build:
      context: .
      dockerfile: Webapp/Dockerfile
      target: debug
    ports:
      - 5000:5000
      - 5002:5001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:5000;http://*:5001
      - ASPNETCORE_HTTPS_PORT=5001
    volumes:
      - .:c:\new_src
